# Generated by Django 4.2.14 on 2024-08-01 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('client', models.CharField(max_length=20)),
                ('attorney', models.CharField(max_length=20)),
                ('date_opened', models.DateField()),
                ('date_closed', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('case_status', models.CharField(choices=[('A', 'Open-Active'), ('I', 'Open-Inactive'), ('C', 'Closed')], default='A', max_length=1)),
                ('case_stage', models.CharField(choices=[('1', 'Intake'), ('2', 'Complaint'), ('3', 'Pre-Trial Motions/Discovery'), ('4', 'Trial Preparation'), ('5', 'Trial'), ('6', 'Mediation'), ('7', 'Arbitration'), ('8', 'Settlement'), ('9', 'MISC')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('task_type', models.CharField(choices=[('1', 'Research'), ('2', 'Draft Motion'), ('3', 'Draft Correspondence'), ('4', 'Hearing'), ('5', 'Administrative'), ('6', 'Status call'), ('7', 'Discovery'), ('8', 'Doc Review'), ('9', 'MISC')], default='1', max_length=1)),
                ('task_status', models.CharField(choices=[('O', 'Open'), ('C', 'Complete')], default='O', max_length=1)),
                ('task_description', models.TextField(max_length=500)),
                ('date_created', models.DateField()),
                ('date_closed', models.DateField()),
                ('estimated_time', models.IntegerField()),
                ('actual_time', models.IntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.case')),
            ],
        ),
    ]
