# Generated by Django 4.2.14 on 2024-08-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['case_status']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['task_status']},
        ),
    ]
