# Generated by Django 4.2.14 on 2024-08-07 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_case_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_opened',
            field=models.DateField(blank=True, default=datetime.date(2024, 8, 7), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.date(2024, 8, 7), null=True),
        ),
    ]
